name: GitPullPlugin
version: '${project.version}'
main: net.hsa12.gitpullplugin.GitPullPlugin
api-version: 1.19
authors: [ HsaSheep ]
description: git pull datapack "hscom".
website: hsa12.net
#---
commands:
  pull:
    description: git pull datapack "hscom".
    usage: '/ : pull datapack.'